# File generated by Flopy version 3.3.2 on 10/22/2020 at 09:30:13.
BEGIN attributes
  NAMES  CHDHEAD
  METHODS  LINEAREND
END attributes

BEGIN timeseries
       0.00000000       0.00000000
     307.00000000       1.00000000
     791.00000000       5.00000000
    1000.00000000       2.00000000
END timeseries

