# File generated by Flopy version 3.3.2 on 10/22/2020 at 09:30:13.
BEGIN attributes
  NAMES  FLOWRATE
  METHODS  LINEAREND
END attributes

BEGIN timeseries
       0.00000000    2000.00000000
     307.00000000    6000.00000000
     791.00000000    5000.00000000
    1000.00000000    9000.00000000
END timeseries

